services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: fip-context
      POSTGRES_PASSWORD: camilleLaBG
    user: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - 127.0.0.1:5432:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: